# Generated by Django 4.2 on 2023-04-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira_rest', '0003_room_desk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jira_rest.desk')),
            ],
        ),
    ]
